### ISSUE TITLE
Exception in spwan

### ISSUE THREAD

**Issue by rgaiacs** [gesiscss/orc2#3]
```
[W 2023-04-28 08:57:40.145 JupyterHub base:1030] 2 consecutive spawns failed.  Hub will exit if failure count reaches 5 before succeeding
[E 2023-04-28 08:57:40.145 JupyterHub gen:630] Exception in Future <Task finished name='Task-15076' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.9/site-packages/jupyterhub/handlers/base.py:954> exception=TimeoutError('pod gesis/jupyter-astrobiomike-2dbinder-2dr-2dbasics-2djff8k1ry did not start in 300 seconds!')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/tornado/gen.py", line 625, in error_callback
        future.result()
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/handlers/base.py", line 961, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/user.py", line 850, in spawn
        raise e
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/user.py", line 747, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.9/site-packages/kubespawner/spawner.py", line 2732, in _start
        await exponential_backoff(
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/utils.py", line 236, in exponential_backoff
        raise asyncio.TimeoutError(fail_message)
    asyncio.exceptions.TimeoutError: pod gesis/jupyter-astrobiomike-2dbinder-2dr-2dbasics-2djff8k1ry did not start in 300 seconds!
```

@minrk should I report this upstream to JupyterHub?

**Comment by minrk** [comment]
No, this is likely a problem with the cluster's performance, not actually being able to launch pods in a reasonable amount of time (image pull very likely).

**Comment by rgaiacs** [comment]
Provide large disk mount point to Docker-inside-Docker (see 174a7621f116d99be26c9ae32c860dce2f6f1395) resolved the problem.
